agent_timeout: 300
allow_dirty: false
auto_merge: false
bash_timeout: 600
cleanup: true
description: ""
detached: false
docker_timeout: 600
feature_flags:
    new-feature:
        description: My new feature
        enabled: true
git_user_email: recac-agent@example.com
git_user_name: RECAC Agent
image: ghcr.io/process-failed-successfully/recac-agent:latest
jira: ""
jira_label: ""
manager_first: false
manager_frequency: 5
max_agents: 1
max_iterations: 20
max_parallel_tickets: 1
metrics_port: 2112
mock: false
mock-agent: false
model: gemini-pro
name: ""
notifications:
    slack:
        channel: '#general'
        enabled: false
        events:
            on_failure: true
            on_project_complete: true
            on_start: true
            on_success: true
            on_user_interaction: true
orchestrator:
    agent_model: mistralai/devstral-2512:free
    agent_provider: openrouter
    image: ghcr.io/process-failed-successfully/recac-agent:latest
    image_pull_policy: Always
    interval: 1m0s
    jira_label: recac-agent
    jira_query: ""
    mode: local
    namespace: default
    poller: jira
    watch_dir: ""
    work_file: work_items.json
path: ""
project: ""
provider: gemini
repo_url: ""
skip_qa: false
stream: false
summary: ""
task_max_iterations: 10
timeout: 300
verbose: false
